### ISSUE TITLE
Abrir dataset INEGI - Directorio Estadístico Nacional de Unidades Económicas

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#12]
Abrir dataset [INEGI - Directorio Estadístico Nacional de Unidades Económicas](http://www3.inegi.org.mx/sistemas/mapa/denue/default.aspx), solicitado por [Derpy Noe](https://twitter.com/noe_dgz)

**Comment by tlacoyodefrijol** [comment]
El dataset está aquí @poguez

http://www3.inegi.org.mx/sistemas/descarga/?c=200

**Comment by hecerinc** [comment]
Modificar la entrada en el sitio apertura.datamx.io (status/link)

**Comment by Eflores89** [comment]
Pueden acceder a datos del denue con el paquete "inegiR" en R: www.enelmargen.org/inegiR
