### ISSUE TITLE
Abrir dataset San Pedro (NL) - Permisos de Alcohol

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#125]
Abrir dataset [San Pedro (NL) - Permisos de Alcohol](http://www.sanpedro.gob.mx/transparencia/PermisosAutorizados/2014/Alcoholes.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/san-pedro-nl-padron-alcoholes
