### ISSUE TITLE
Abrir dataset tabuladores salariales Secretaría de Salud ISAPEG

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#126]
Abrir dataset [tabuladores salariales Secretaría de Salud ISAPEG](http://transparencia.guanajuato.gob.mx/tabulador.php?s_ten_id=4&s_puesto=&s_nivel=&Button_DoSearch=Buscar&tabuladorPage=1), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/guanajuato-tabuladores-salariales-secretaria-salud
