### ISSUE TITLE
Abrir dataset tabuladores salariales Secretar'ia de Educación de Guanajuato SEG

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#127]
Abrir dataset [tabuladores salariales Secretar'ia de Educación de Guanajuato SEG](http://transparencia.guanajuato.gob.mx/tabulador.php?s_ten_id=8&s_puesto=&s_nivel=&Button_DoSearch=Buscar), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/guanajuato-tabuladores-salariales-secretaria-educacion
