### ISSUE TITLE
Abrir dataset Bienes adquiridos y precio 2014 Gto.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#137]
Abrir dataset [Bienes adquiridos y precio 2014 Gto.](http://finanzas.guanajuato.gob.mx/c_adquisiciones/index.php), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/guanajuato-bienes-adquiridos-y-precio-2014
