### ISSUE TITLE
Abrir dataset San Pedro (NL) - Permisos de Espectáculos

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#138]
Abrir dataset [San Pedro (NL) - Permisos de Espectáculos](http://www.sanpedro.gob.mx/transparencia/a10F17f.asp), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/san-pedro-nl-permisos-espectaculos
