### ISSUE TITLE
Abrir dataset San Pedro (NL) - Padrón de Proveedores (Personas físicas)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#140]
Abrir dataset [San Pedro (NL) - Padrón de Proveedores (Personas físicas)](http://www.sanpedro.gob.mx/transparencia/a10F18f.asp), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en http://datamx.io/dataset/proveedores-san-pedro-nl-personas-fisicas
