### ISSUE TITLE
Abrir dataset San Pedro (NL) - Indicadores de Gestión (Segundo trimestre)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#143]
Abrir dataset [San Pedro (NL) - Indicadores de Gestión (Segundo trimestre)](http://www.sanpedro.gob.mx/transparencia/Tesoreria/finanzasMunicipales14/IndicadoresSindesPrimerTrimestre.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://apertura.datamx.io/solicitud/141/san-pedro-nl-indicadores-de-gestion-segundo-trimestre

**Comment by tsdl** [comment]
@paulinabustos Este issue que había quedado pendiente ya fue resuelto.
