### ISSUE TITLE
Abrir dataset San Pedro (NL) - Indicadores de Gestión (Tercer trimestre)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#144]
Abrir dataset [San Pedro (NL) - Indicadores de Gestión (Tercer trimestre)](http://www.sanpedro.gob.mx/transparencia/Tesoreria/finanzasMunicipales14/IndicadoresTercerTrimestre_ServiciosPublicos.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar a tsdl (@ts_dl)

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/san-pedro-nl-indicadores-2014-tercer-trimestre

**Comment by tsdl** [comment]
@paulinabustos Este issue que había quedado pendiente ya fue resuelto.
