### ISSUE TITLE
Abrir dataset San Pedro (NL) - Deuda Pública Municipal

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#146]
Abrir dataset [San Pedro (NL) - Deuda Pública Municipal](http://www.sanpedro.gob.mx/transparencia/a14F4f.asp), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a @ts_dl

**Comment by tsdl** [comment]
Datos abiertos en http://datamx.io/dataset/san-pedro-nl-deuda-publica-2014-2015

**Comment by paulinabustos** [comment]
@tsdl ¿Puedes aceptar la invitación que te enviamos para asignarte y cerrar este issue? Saludos y gracias por participar.
