### ISSUE TITLE
Abrir dataset INCIDENCIA DELICTIVA B.C (2015)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#251]
Abrir dataset [INCIDENCIA DELICTIVA B.C (2015)](http://www.seguridadbc.gob.mx/Estadisticas/2015/inci_Estado.pdf?id=225371612), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-incidencia-delictiva-2015
