### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (noviembre)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#256]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (noviembre)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/CHEQUES%20ENVIADOS-Oct%202014.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-noviembre-2014
Nota: El enlace al archivo XLS en la petición es incorrecto. El URL correcto a los datos de noviembre puede encontrarse ahora en el conjunto de datos.
