### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (octubre)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#257]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (octubre)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/CHEQUES%20ENVIADOS-Oct%202014.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-octubre-2014
