### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (septiembre)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#258]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (septiembre)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XIII/archivosTransparencia/CHEQUES%20ENVIADOS-SEP%202014.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-septiembre-2014
