### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (agosto)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#259]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (agosto)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/CHEQUES%20ENVIADOS-AGO%202014.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-agosto-2014
