### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (junio)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#261]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (junio)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/chequesenviadosjun2014.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-junio-2014
