### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (mayo)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#262]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (mayo)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/CHEQUES%20ENVIADOS-MAY%202014%20Firmado.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-mayo-2014
