### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (abril)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#263]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (abril)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/IX/archivosTransparencia/2014_Abr_CHEQUES.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-abril-2014
