### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (febrero)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#265]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (febrero)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/2014_Feb_Cheques.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-febrero-2014
