### ISSUE TITLE
Abrir dataset Apodaca (NL) - Cheques enviados 2014 (enero)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#266]
Abrir dataset [Apodaca (NL) - Cheques enviados 2014 (enero)](http://www.apodaca.gob.mx/archivos/pdf/transparencia/articulo10/XII/archivosTransparencia/CHEQUES%20ENVIADOS-ENE%202014.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/apodaca-cheques-enero-2014
