### ISSUE TITLE
Abrir dataset PADRON DE AUTORIDADES AMBIENTALES B.C

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#267]
Abrir dataset [PADRON DE AUTORIDADES AMBIENTALES B.C](http://www.spabc.gob.mx/views/files/tmp/padron-auditores-2014-15.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-padron-auditores-ambientales-2014-2015
