### ISSUE TITLE
Abrir dataset PADRÓN ESTATAL DE PERITOS EN MONITOREO B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#268]
Abrir dataset [PADRÓN ESTATAL DE PERITOS EN MONITOREO B.C.](http://www.spabc.gob.mx/views/files/tmp/PADRON-ESTATAL-DE-PERITOS-EN-MONITOREO.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-padron-peritos-2013-2014
