### ISSUE TITLE
Abrir dataset PADRÓN ESTATAL DE LABORATORIOS AMBIENTALES B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#269]
Abrir dataset [PADRÓN ESTATAL DE LABORATORIOS AMBIENTALES B.C.](http://www.spabc.gob.mx/views/files/tmp/Padron-de-Laboratorios.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-padron-de-laboratorios-ambientales-2013
