### ISSUE TITLE
Abrir dataset PRECIOS DE TRAMITES AMBIENTALES B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#270]
Abrir dataset [PRECIOS DE TRAMITES AMBIENTALES B.C.](http://www.spabc.gob.mx/views/files/tmp/PRECIOS-MARZO-2015.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-precio-tramites-ambientales
