### ISSUE TITLE
Abrir dataset ESTATUS DE TRAMITES PREVENCION A LA CONTAMINACION B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#271]
Abrir dataset [ESTATUS DE TRAMITES PREVENCION A LA CONTAMINACION B.C.](http://www.spabc.gob.mx/views/files/tmp/concentrado-aguas-emisiones-tj-mxl-ens-160712.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-estatus-tramites-prevencion-contaminacion
