### ISSUE TITLE
Abrir dataset ESTATUS DE TRAMITES DE LICENCIAS DE RME B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#272]
Abrir dataset [ESTATUS DE TRAMITES DE LICENCIAS DE RME B.C.](http://www.spabc.gob.mx/views/files/tmp/ESTATUS-DE-TRAMITES-DE-PRESTADORES-RME-tj-mxl-ens-AGO12.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-estatus-tramites-licencias-rme
