### ISSUE TITLE
Abrir dataset Ingresos Totales B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#273]
Abrir dataset [Ingresos Totales B.C.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/transparencia_fiscal/rendicion/desagregacion_ingresos/Real%202002-2010%20DESAGREGADO.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-comparativo-de-ingresos-2002-2011

**Comment by paulinabustos** [comment]
@tsdl La liga no funciona.

**Comment by tsdl** [comment]
@paulinabustos Liga corregida en el comentario anterior.
