### ISSUE TITLE
Abrir dataset Ingresos PROPIOS B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#274]
Abrir dataset [Ingresos PROPIOS B.C.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/transparencia_fiscal/estadisticas/ingresos%20PROPIOS%20AVANCE%202010.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-concentrado-de-ingresos-2002-2011

**Comment by paulinabustos** [comment]
@tsdl Me aparecen que no existen.

**Comment by tsdl** [comment]
@paulinabustos Disculpas. Había modificado el URL. Ya está corregido en el comentario anterior.
