### ISSUE TITLE
Abrir dataset Clasificación funcional del gasto B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#275]
Abrir dataset [Clasificación funcional del gasto B.C.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/transparencia_fiscal/estadisticas/clasFuncionalGto.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-cierres-presupuestales-2001-2011-clasificacion-funcional

**Comment by paulinabustos** [comment]
@tsdl Me aparece que no existen.

**Comment by tsdl** [comment]
Disculpas. Había modificado el URL. Ya está corregido en el link anterior.
