### ISSUE TITLE
Abrir dataset Clasificación económica del gasto B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#276]
Abrir dataset [Clasificación económica del gasto B.C.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/transparencia_fiscal/estadisticas/clasEconGto.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-clasificacion-por-objeto-del-gasto-2001-2011
Por el momento sólo son posibles la visualización y la descarga de los datos debido a un error al subir el archivo al Data Store.
