### ISSUE TITLE
Abrir dataset Inversión pública Nivel Financiero b.c.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#277]
Abrir dataset [Inversión pública Nivel Financiero b.c.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/spf/ip/transparencia/BC-NF-4TO%20TRIM%202014%20-SFU%20v2.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-inversion-publica-nivel-financiero-2014-trimestre4
