### ISSUE TITLE
Abrir dataset Inversión pública gestión de proyectos b.c.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#278]
Abrir dataset [Inversión pública gestión de proyectos b.c.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/spf/ip/transparencia/BC%204TO%20TRIM%202014%20-%20SFU%20v2.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-situacion-economica-finanzas-deuda-publica
