### ISSUE TITLE
Abrir dataset Inversión Pública Recurso FAISM

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#280]
Abrir dataset [Inversión Pública Recurso FAISM](http://www.bajacalifornia.gob.mx/bcfiscal/2012/spf/ip/transparencia/4TO%20TRIMESTRE%20DE%202014%20-%20FAISM%20-%20MPIOS%20(res).xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-ejercicio-2014-trim4-recurso-faism
