### ISSUE TITLE
Abrir dataset Presupuesto Inicial 2014 B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#281]
Abrir dataset [Presupuesto Inicial 2014 B.C.](http://www.bajacalifornia.gob.mx/bcfiscal/2012/spf/ip/transparencia/Presupuesto%20inicial%202014.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-proyectos-de-inversion-2014
