### ISSUE TITLE
Abrir dataset Aforo Carretera Escénica (2000-2011)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#283]
Abrir dataset [Aforo Carretera Escénica (2000-2011)](http://www.descubrebajacalifornia.com/files/estudios-y-estadisticas/demanda/AFORO-VEHICULAR2000-2011.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-aforo-vehiculos-carretera-escenica-2000-2011
