### ISSUE TITLE
Abrir dataset Indicadores turísticos 2012 B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#284]
Abrir dataset [Indicadores turísticos 2012 B.C.](http://www.descubrebajacalifornia.com/files/estudios-y-estadisticas/demanda/Indicadores/Indicadores-al-mes-de-Septiembre-2012.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-indicadores-turisticos-2012
