### ISSUE TITLE
Abrir dataset Ocupación Hotelera (2003-2011) B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#285]
Abrir dataset [Ocupación Hotelera (2003-2011) B.C.](http://www.descubrebajacalifornia.com/files/estudios-y-estadisticas/demanda/OCUPACION-HOTELERA2003-2011.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-ocupacion-hotelera-destino-2003-2006
