### ISSUE TITLE
Abrir dataset Arribo de Cruceros Ensenada (2003-2011)

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#286]
Abrir dataset [Arribo de Cruceros Ensenada (2003-2011)](http://www.descubrebajacalifornia.com/files/estudios-y-estadisticas/demanda/ARRIBOS-DE-CRUCEROS2003-2011.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/bc-arribo-cruceros-turisticos-ensenada-2003-2011
* Falta el API, pero marca un error al subir al Data Store. Por lo pronto está disponible la visualización y la descarga.
