### ISSUE TITLE
Abrir dataset Cruces Fronterizos (2005-2011) B.C.

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#287]
Abrir dataset [Cruces Fronterizos (2005-2011) B.C.](http://www.descubrebajacalifornia.com/files/estudios-y-estadisticas/demanda/Cruces-Fronterizos/Cruces2011.pdf), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/baja-california-cruces-fronterizos-2011
