### ISSUE TITLE
Abrir dataset FIFOMI Información de Bienes Muebles al 31 de diciembre de 2014

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#288]
Abrir dataset [FIFOMI Información de Bienes Muebles al 31 de diciembre de 2014](http://www.fifomi.gob.mx/web/images/fifomi/documentos/infgeneral/informes/2-Formato-Bienes-muebles.xls), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/fifomi-bienes-muebles-31-diciembre-2014
