### ISSUE TITLE
Abrir dataset AMIA ventas al publico

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#290]
Abrir dataset [AMIA ventas al publico](http://www.amia.com.mx/ventasp.html), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/amia-venta-al-publico
