### ISSUE TITLE
Abrir dataset AMIA producción total

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#291]
Abrir dataset [AMIA producción total](http://www.amia.com.mx/prodtot.html), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/amia-produccion-total
