### ISSUE TITLE
Abrir dataset AMIA exportación por región

### ISSUE THREAD

**Issue by AperturaDeDatos** [CodeandoMexico/Apertura-de-Datos#294]
Abrir dataset [AMIA exportación por región](http://www.amia.com.mx/expregion.html), solicitado por [escuadronestudiantil](https://twitter.com/student_squad)

**Comment by tsdl** [comment]
Asignar este issue a tsdl

**Comment by tsdl** [comment]
Datos abiertos en: http://datamx.io/dataset/amia-exportacion-por-region
